import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/components/theme-provider';
import Link from 'next/link';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PokéFinder",
  description: "Generated by create next app",
};

// Providers wrap around our application and give them access to data
// NextThemesProvider - Give our application access to light/dark mode
// Providers are generally on the client side ("use client")
//switch from light mode to dark mode <-- user interaction / needs client to exist
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <main className="flex min-h-screen flex-col items-center p-24 bg-black">
            <div className="z-5 w-full max-w-5xl items-center text-sm lg:flex">
              <Link href="/" className="bg-black">
                <h2 className="text-5xl text-bold"><b>PokéFinder</b></h2>
              </Link>
            </div>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
